### ISSUE TITLE
Shell config?

### ISSUE THREAD

**Issue by jdsimcoe** [cgsawtell/hyperterm-adventurous#2]
What is your shell config? Love the colors.

**Comment by cgsawtell** [comment]
I'm using zsh and 'oh my zsh' with the agnoster theme:)

**Comment by jdsimcoe** [comment]
Cool!--jdsimcoe.comOn Fri, Oct 07, 2016 at 12:09 AM, Caleb Sawtellnotifications@github.comwrote:I'm using zsh and 'oh my zsh' with the agnoster :)—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
